city_engine/urls.py
# from django.conf.urls import url
from django.urls import path

from . import views

app_name = "city_engine"

urlpatterns = [
    path(r"main/", views.main_view, name="main"),
    path(r"main/turn_calculations/", views.turn_calculations, name="turn_calculations"),
    path(
        r"build/<row>/<col>/<build_type>/",
        views.build,
    ),
    path(
        r"build_resident/<row>/<col>/<max_population>/",
        views.build_resident,
    ),
    path(r"main/resources/", views.resources, name="resources"),
]

cou/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("player.urls")),
    path("", include("city_engine.urls")),
    path("", include("map_engine.urls"))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

player/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "player"

urlpatterns = [
    path(r"", views.main_page, name="main_page"),
    path(r"signup/", views.signup, name="signup"),
    path(
        r"account_activation_sent/",
        views.account_activation_sent,
        name="account_activation_sent",
    ),
    # url(
    #     r"^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
    #     views.activate,
    #     name="activate",
    # ),
    path(r"login/", auth_views.LoginView, name="login"),
    path(r"logout/", auth_views.LogoutView, {"next_page": "/"}, name="logout"),
    path(r"logout-then-login/", auth_views.logout_then_login, name="logout_then_login"),
]

city_engine/models.py
import decimal

from django.apps import apps
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models

from city_engine.temp_models import (
    TempResidential,
    TempTradeDistrict,
    DataContainersWithEmployees,
    TempRopePlant,
    TempCoalPlant,
    TempAnimalFarm,
    TempPowerPlant,
    TempSewageWorks,
    TempWaterTower,
    TempFarm,
    TempBuild,
    TempWindPlant,
    TempDumpingGround,
    TempClinic,
    TempFireStation,
    TempPoliceStation,
    TempPrison
)
from cou.global_var import (
    ELEMENTARY,
    COLLEGE,
    STANDARD_RESIDENTIAL_ZONE_COST_PER_RESIDENT,
)
from map_engine.models import Field
from map_engine.models import Map
from player.models import Profile


class Trash(models.Model):
    size = models.PositiveIntegerField(default=0)
    time = models.PositiveIntegerField(default=0)

    content_type = models.ForeignKey(ContentType, on_delete=models.SET_NULL, null=True)
    object_id = models.PositiveIntegerField()
    content_objects = GenericForeignKey()


class City(models.Model):
    player = models.ForeignKey(Profile, on_delete=True)
    map = models.ForeignKey(Map, on_delete=True)
    name = models.TextField(max_length=15, unique=True)
    cash = models.DecimalField(default=1000000, decimal_places=2, max_digits=20)
    trade_zones_taxation = models.FloatField(default=0.05)
    publish = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.name


class Building(models.Model):
    temp_model = TempBuild
    city = models.ForeignKey(City, on_delete=True)
    city_field = models.ForeignKey(Field, on_delete=True)
    cash = models.DecimalField(default=0, decimal_places=2, max_digits=20)
    if_under_construction = models.BooleanField(default=True)
    build_cost = models.PositiveIntegerField(default=0)
    maintenance_cost = models.PositiveIntegerField(default=0)
    build_time = models.PositiveIntegerField()
    current_build_time = models.PositiveIntegerField(default=1)
    trash = GenericRelation(Trash)
    # Pollution
    pollution_rate = models.FloatField(default=0.0)
    pollution_product = models.PositiveIntegerField(default=0)
    recycling = models.PositiveIntegerField(default=0)

    class Meta:
        abstract = True

    def build_status(self):
        if self.current_build_time < self.build_time:
            self.current_build_time += 1
        elif self.current_build_time == self.build_time:
            self.if_under_construction = False


class BuldingsWithWorkes(Building):
    temp_model = DataContainersWithEmployees
    profession_type_provided = models.CharField(default="", max_length=1)
    elementary_employee_needed = models.PositiveIntegerField(default=0)
    college_employee_needed = models.PositiveIntegerField(default=0)
    phd_employee_needed = models.PositiveIntegerField(default=0)
    employee = GenericRelation(
        to="citizen_engine.Citizen",
        object_id_field="workplace_object_id",
        content_type_field="workplace_content_type",
    )

    def calculate_price_of_good(self, workers_costs, size_of_production):
        if workers_costs and size_of_production:
            return workers_costs / decimal.Decimal(size_of_production)
        return 0

    class Meta:
        abstract = True


class Residential(Building):
    temp_model = TempResidential
    name = models.CharField(max_length=20, default="Budynek Mieszkalny")
    population = models.PositiveIntegerField(default=0)
    max_population = models.PositiveIntegerField(default=0)
    build_time = models.PositiveIntegerField(default=0)
    build_cost = models.PositiveIntegerField(default=0)
    resident = GenericRelation(
        to="citizen_engine.Citizen",
        object_id_field="resident_object_id",
        content_type_field="resident_content_type",
    )

    class Meta:
        abstract = True


class StandardLevelResidentialZone(Residential):
    temp_model = TempResidential
    name = models.CharField(max_length=30, default="Normalna dzielnica mieszkalna")

    def self__init(self, max_population):
        self.max_population = 1 if max_population <= 0 else max_population
        self.build_time = 1 if max_population <= 4 else int(max_population / 4)
        self.build_cost = STANDARD_RESIDENTIAL_ZONE_COST_PER_RESIDENT * max_population


class ProductionBuilding(BuldingsWithWorkes):
    name = models.CharField(max_length=20, default="Strefa przemysłowa")
    profession_type_provided = models.CharField(
        default="Pracownik strefy przemysłowej", max_length=30
    )

    build_time = models.PositiveIntegerField(default=1)
    build_cost = models.PositiveIntegerField(default=100)
    maintenance_cost = models.PositiveIntegerField(default=10)
    elementary_employee_needed = models.PositiveIntegerField(default=20)

    def build_status(self):
        if self.current_build_time < self.build_time:
            self.current_build_time += 1
        elif self.current_build_time == self.build_time:
            self.if_under_construction = False


class PowerPlant(BuldingsWithWorkes):
    temp_model = TempPowerPlant
    name = models.CharField(max_length=20)
    power_nodes = models.PositiveIntegerField(default=0)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class WindPlant(PowerPlant):
    temp_model = TempWindPlant
    name = models.CharField(default="Elektrownia wiatrowa", max_length=20)
    profession_type_provided = models.CharField(
        default="Pracownik elektrowni wiatrowej", max_length=30
    )
    build_time = models.PositiveIntegerField(default=3)
    build_cost = models.PositiveIntegerField(default=100)
    maintenance_cost = models.PositiveIntegerField(default=10)
    pollution_rate = models.FloatField(default=1.8)
    elementary_employee_needed = models.PositiveIntegerField(default=5)

    def build_status(self):
        if self.current_build_time < self.build_time:
            self.current_build_time += 1
        elif self.current_build_time == self.build_time:
            self.if_under_construction = False
            self.power_nodes = 1


class RopePlant(PowerPlant):
    temp_model = TempRopePlant
    name = models.CharField(default="Elektrownia na ropę", max_length=20)
    profession_type_provided = models.CharField(
        default="Pracownik elektrowni na ropę", max_length=30
    )
    build_time = models.PositiveIntegerField(default=5)
    build_cost = models.PositiveIntegerField(default=200)
    maintenance_cost = models.PositiveIntegerField(default=20)
    pollution_rate = models.FloatField(default=1.3)
    elementary_employee_needed = models.PositiveIntegerField(default=10)

    def build_status(self):
        if self.current_build_time < self.build_time:
            self.current_build_time += 1
        elif self.current_build_time == self.build_time:
            self.if_under_construction = False
            self.power_nodes = 1


class CoalPlant(PowerPlant):
    temp_model = TempCoalPlant
    name = models.CharField(default="Elektrownia węglowa", max_length=20)
    profession_type_provided = models.CharField(
        default="Pracownik elektrowni węglowej", max_length=30
    )
    build_time = models.PositiveIntegerField(default=4)
    build_cost = models.PositiveIntegerField(default=150)
    maintenance_cost = models.PositiveIntegerField(default=15)
    pollution_rate = models.FloatField(default=1.5)
    elementary_employee_needed = models.PositiveIntegerField(default=15)

    def build_status(self):
        if self.current_build_time < self.build_time:
            self.current_build_time += 1
        elif self.current_build_time == self.build_time:
            self.if_under_construction = False
            self.power_nodes = 1


class Waterworks(BuldingsWithWorkes):
    temp_model = TempWaterTower
    name = models.CharField(max_length=20)
    pollution_rate = models.FloatField(default=0.5)

    class Meta:
        abstract = True


class WaterTower(Waterworks):
    temp_model = TempWaterTower
    name = models.CharField(default="Wieża ciśnień", max_length=20)
    profession_type_provided = models.CharField(
        default="Pracownik wieży ciśnień", max_length=30
    )
    build_time = models.PositiveIntegerField(default=1)
    build_cost = models.PositiveIntegerField(default=50)
    maintenance_cost = models.PositiveIntegerField(default=5)
    elementary_employee_needed = models.PositiveIntegerField(default=5)

    def build_status(self):
        if self.current_build_time < self.build_time:
            self.current_build_time += 1
        elif self.current_build_time == self.build_time:
            self.if_under_construction = False


class SewageWorks(BuldingsWithWorkes):
    temp_model = TempSewageWorks
    name = models.CharField(default="Oczyszczalnia ścieków", max_length=30)
    profession_type_provided = models.CharField(
        default="Pracownik oczyszczalni", max_length=30
    )
    build_time = models.PositiveIntegerField(default=2)
    build_cost = models.PositiveIntegerField(default=75)
    maintenance_cost = models.PositiveIntegerField(default=10)
    pollution_rate = models.FloatField(default=2.0)
    elementary_employee_needed = models.PositiveIntegerField(default=3)

    def build_status(self):
        if self.current_build_time < self.build_time:
            self.current_build_time += 1
        elif self.current_build_time == self.build_time:
            self.if_under_construction = False


class Farm(BuldingsWithWorkes):
    temp_model = TempFarm
    build_time = models.PositiveIntegerField(default=1)
    build_cost = models.PositiveIntegerField(default=200)
    maintenance_cost = models.PositiveIntegerField(default=20)
    elementary_employee_needed = models.PositiveIntegerField(default=10)

    time_to_grow_from = models.PositiveIntegerField(default=0)

city_engine/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import render
from django.utils.safestring import mark_safe

from city_engine.main_view_data.board import Board, HexDetail
from city_engine.models import City, StandardLevelResidentialZone
from cou.turn_data import AbstractAdapter
from cou.turn_data import RootClass
from player.models import Message
from player.models import Profile
from .turn_data.build import build_building, build_resident_zone
from .turn_data.calculation import TurnCalculation
from map_engine.map_viewer.main import HexTable
from map_engine.models import Field


@login_required
def main_view(request):
    profile = Profile.objects.get(user_id=request.user.id)
    city = City.objects.get(player=profile)
    rc = RootClass(city, request.user)
    new_board = HexTable(Field.objects.filter(player=profile), rc)
    new_hex_detail = HexDetail(city, rc)

    total_cost_of_main = sum(b.maintenance_cost for b in rc.list_of_buildings)
    building_under_construction = [b for b in rc.list_of_buildings if b.if_under_construction is True]

    build_exception = [StandardLevelResidentialZone]
    list_of_buildings_class = [
        sub.__name__
        for sub in AbstractAdapter().get_subclasses_of_all_buildings()
        if sub not in build_exception
    ]

    return render(
        request,
        "main_view.html",
        {
            "city": city,
            "profile": profile,
            "hex_table": mark_safe(new_board.hex_table),
            "hex_detail_info_table": mark_safe(new_hex_detail.hex_detail_info_table),
            "buildings": (
                rc.list_of_buildings[b]
                for b in rc.list_of_buildings
                if b.if_under_construction == False
            ),
            "buildings_under_construction": building_under_construction,
            "total_cost_of_maintenance": total_cost_of_main,
            "citizen": (rc.citizens_in_city[c] for c in rc.citizens_in_city),
            "list_of_buildings_class": list_of_buildings_class,
            "families": (rc.families[f] for f in rc.families),
        },
    )


@login_required
def resources(request):
    profile = Profile.objects.get(user_id=request.user.id)
    city = City.objects.get(player=profile)
    rc = RootClass(city, request.user)
    market_resources = rc.market.resources.items()
    companies_goods = {c: rc.companies[c].goods.items() for c in rc.companies}.items()
    return render(
        request,
        "resources_view.html",
        {
            "city": city,
            "market_resources": market_resources,
            "companies_goods": companies_goods,
        },
    )


@login_required
def turn_calculations(request):
    profile = Profile.objects.get(user_id=request.user.id)
    city = City.objects.get(player=profile)
    data = RootClass(city, request.user, is_turn_calculation=True)
    TurnCalculation(city, data, profile).run()
    # return render(request, 'city_calculation_view.html')
    return HttpResponseRedirect("/main")


@login_required
def build(request, row, col, build_type):
    build_building(request, row, col, build_type)
    return HttpResponseRedirect("/main")


@login_required
def build_resident(request, row, col, max_population):
    build_resident_zone(request, row, col, max_population)
    return HttpResponseRedirect("/main")

city_engine/templates/base_city.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/style.css"  type="text/css" media="screen">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <title>{% block title %}{% endblock %}</title>
    {% block script %}{% endblock %}
</head>
<body>
<main class="container">
    <h1>Ekran base dla Gry</h1>
    <ul>
        <li><a href="{% url 'city_engine:main' %}">Miasto</a></li>
        <li><a href="{% url 'city_engine:resources' %}">Surowce</a></li>
    </ul>
    {% block content %}
    {% endblock %}
</main>
{% block jsScript %}

{% endblock %}
</body>
</html>

city_engine/templates/city_calculation_view.html
{% extends 'base_city.html' %}

{% block title %}Kalkulacja Tury{% endblock %}

{% block content %}
<h1>Próbny widok dla kalkulacji</h1>


{% endblock %}

city_engine/templates/main_view.html
{% extends 'base_city.html' %}
{% load staticfiles %}

{% block script %}
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% endblock %}

{% block title %}Miasto {{ city.name }}{% endblock %}

{% block content %}

{% if request.user.is_authenticated %}
    <p>Witaj, {{ request.user.username }}!</p>
    <p><a href="{% url 'player:logout' %}">Wyloguj</a></p>
                    {% else %}
    <p><a href="{% url 'player:login' %}">Zaloguj</a></p>
    {% endif %}

<p>Miasto: {{ city.name }}</p>
<p>Pieniądze: {{ city.cash }}</p>
<p>Masa: {{ city.mass }}</p>

<h1>Statystyki</h1>

<p>{{ profile.current_turn }}/12</p>
{% if city.cash > 0 %}
    {% if profile.current_turn <= 11 %}
        <button><a href="{% url 'city_engine:turn_calculations' %}">Kolejna tura</a></button>
{% endif %}
{% endif %}

{% if city.cash <= 0 %}
<h1>BANKRUT</h1>
{% endif %}


<div class="container">
    <h2>Dynamic Tabs</h2>
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#home">Home</a></li>
        <li><a data-toggle="tab" href="#menu1">Mieszkańcy</a></li>
        <li><a data-toggle="tab" href="#menu2">Budynki</a></li>
        <li><a data-toggle="tab" href="#menu3">Budynki w trakcie budowy</a></li>
        <li><a data-toggle="tab" href="#menu4">Rodziny</a></li>
    </ul>
    <div class="tab-content">
        <div id="home" class="tab-pane fade in active">
            <h3>HOME</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
        <div id="menu1" class="tab-pane fade">
            <h3>Mieszkańcy</h3>
            <table class="table">
                <thead>
                <tr>
                    <th>Imię</th>
                    <th>Nazwisko</th>
                    <th>Wiek</th>
                    <th>Płeć</th>
                    <th>Miejsce pracy</th>
                    <th>Pieniądze</th>
                    <th>Zawód</th>
                    <th>Wykształcenie</th>
                    <th>Miejsce zamieszkania</th>
                </tr>
                </thead>
                <tbody>
                {% for c in citizen %}
                <tr>
                    <th>{{ c.ci.name }}</th>
                    <th>{{ c.ci.surname }}</th>
                    <th>{{ c.ci.age }}</th>
                    <th>{{ c.ci.sex }}</th>
                    <th>{{ c.ci.workplace_object }}</th>
                    <th>{{ c.ci.cash }}</th>
                    <th>{{ c.current_profession.name }},{{ c.current_profession.proficiency}}</th>
                    <th>{{ c.current_education }}</th>
                    <th>{{ c.ci.resident_object }}</th>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div id="menu2" class="tab-pane fade">
            <h3>Budynki</h3>
            {% if buildings %}
            <h1><b>Lista budynków</b></h1>
            <table class="table">
                <thead>
                <tr>
                    <th>Nazwa</th>
                    <th>Energia</th>
                    <th>Woda</th>
                </tr>
                </thead>
                <tbody>
                {% for b in buildings %}
                <tr>
                    <th>{{ b.bi.name }}</th>
                    <th>{{ b.bi.energy }}/{{ b.bi.energy_required }}</th>
                    <th>{{b.bi.water }}/{{ b.bi.water_required }}</th>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
        <div id="menu3" class="tab-pane fade">
            <h3>Budynki w trakcie budowy</h3>
            {% if buildings_under_construction %}
            <p><b>Lista budynków w budowie</b></p>
            <table class="table">
                <thead>
                <tr>
                    <th>Budowa</th>
                    <th>Czas</th>
                </tr>
                </thead>
                <tbody>
                {% for b in buildings_under_construction %}
                <tr>
                    <th>{{ b.name }}</th>
                    <th>{{ b.current_build_time }}/{{ b.build_time }}</th>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            {% endif %}
        </div>
        <div id="menu4" class="tab-pane fade">
            <h3>Rodziny</h3>
            <table class="table">
                <thead>
                <tr>
                    <th>Rodzina</th>
                    <th>Członkowie</th>
                    <th>Pieniądze</th>
                </tr>
                </thead>
                <tbody>
                {% for f in families%}
                <tr>
                    {% for fam in f.fi %}
                    <th>{{ fam.surname }}</th>
                    {% endfor %}
                    <th>{{ f.members}}</th>
                    <th>{{ f.cash }}</th>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<button class="hex-change">Zmień hexy</button>

<div id="buildSection">
    <p>Aktywny budynek: {{ activeBuilding }}</p>
    {% for building in list_of_buildings_class %}
    <button v-on:click="filter('{{ building }}')" name="{{ building }}">{{ building }}</button>
    {% endfor %}

    <button v-on:click="filter('StandardLevelResidentialZone')" name="StandardLevelResidentialZone">Strefa mieszkalna $</button>
    <input v-model="numOfResidents" v-bind:class='{unSeen: activeBuilding !== "StandardLevelResidentialZone" }' type="number" placeholder="Ilość mieszkańców">

<div id="board">
    <h1>Plansza wygenerowana z Djagno</h1>
    {{ hex_table }}
</div>
<div id="hexInfoBox">
    <h1>Podgląd hexa</h1>
    {{ hex_detail_info_table }}
</div>
</div>

{% endblock %}

{% block jsScript %}
<script>
    new Vue({
        el: '#buildSection',
        data: {
            isActive: false,
            activeBuilding: '',
            numOfResidents: 0,
        },
        methods: {
            filter: function (typeOfBuilding) {
                if (!this.isActive) {
                    this.activeBuilding = typeOfBuilding;
                    this.isActive = !this.isActive;
                } else if (this.activeBuilding === typeOfBuilding) {
                    this.isActive = !this.isActive;
                    this.activeBuilding = '';
                    this.numOfResidents = 0;
                } else if (this.activeBuilding !== typeOfBuilding) {
                    this.activeBuilding = typeOfBuilding;
                }
            },
            getRowCol: function (rc) {
                if (this.isActive && this.activeBuilding === "StandardLevelResidentialZone") {
                    window.location.replace("/build_resident/" + rc[0] + "/" + rc[1] + "/" + this.numOfResidents);
                } else if (this.activeBuilding) {
                    window.location.replace("/build/" + rc[0] + "/" + rc[1] + "/" + this.activeBuilding + "");
                }
            }
        }
    })
</script>
{% endblock %}

city_engine/templates/resources_view.html
{% extends 'base_city.html' %}
{% load staticfiles %}

{% block script %}
{% endblock %}

{% block title %}Surowce{% endblock %}

{% block content %}
    <h1>Surowce dla miasta {{ city.name }}</h1>
<h2>Towary wyprodukowane przez firmy</h2>

{% for company_name, data in companies_goods %}
<h3>{{ company_name }}</h3>
    {% for good_name, good_container in data %}
    <h4>{{ good_name }}</h4>
    <table class="table">
        <thead>
            <tr>
                <th>Wielkość</th>
                <th>Jakość</th>
                <th>Cena</th>
            </tr>
        </thead>
        <tbody>
            {% for good in good_container.instances %}
            <tr>
                <th>{{ good.size }}</th>
                <th>{{ good.quality }}</th>
                <th>{{ good.price }}</th>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>{{ good_container.total_size }}</th>
                <th>{{ good_container.avg_quality }}</th>
                <th>{{ good_container.avg_price }}</th>
            </tr>
        </tfoot>
    </table>
{% endfor %}
{% endfor %}

<h2>Zasoby dostępne na rynku</h2>
{% for r_name, r_val in market_resources %}
<h3>{{ r_name }}</h3>
    <table class="table">
        <thead>
            <tr>
                <th>Wielkość</th>
                <th>Jakość</th>
                <th>Cena</th>
            </tr>
        </thead>
        <tbody>
            {% for i in r_val.instances %}
            <tr>
                <th>{{ i.size }}</th>
                <th>{{ i.quality }}</th>
                <th>{{ i.price }}</th>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <th>{{ r_val.total_size }}</th>
                <th>{{ r_val.avg_quality }}</th>
                <th>{{ r_val.avg_price }}</th>
            </tr>
        </tfoot>
    </table>
{% endfor %}

{% endblock %}