cou/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("player.urls")),
    path("", include("city_engine.urls")),
    path("", include("map_engine.urls"))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

map_engine/urls.py
from django.urls import path
from . import views

app_name = "map_engine"

urlpatterns = [
    path("list_of_maps/", views.list_of_maps, name="list_of_maps"),
    path("list_of_maps/create_new_map/", views.create_new_map, name="create_new_map"),
    path("list_of_maps/show_map/<map_id>/", views.show_map, name="show_map"),
]

map_engine/models.py
from django.db import models
from cou.global_var import COAL, IRON, URAN, TITAN, MOUNTAIN, SEA, FERTILE
from player.models import Profile
from .temp_models import TempField


class Map(models.Model):
    name = models.CharField(max_length=10)
    rows = models.IntegerField()
    cols = models.IntegerField()


class Field(models.Model):
    temp_model = TempField
    RESOURCES = (
        (COAL, 'Węgiel'),
        (IRON, 'Żelazo'),
        (URAN, 'Uran'),
        (TITAN, 'Tytan')
    )
    TERRAIN = (
        (MOUNTAIN, "Góry"),
        (SEA, "Morze"),
        (FERTILE, "Pola uprawne")
    )
    map = models.ForeignKey(Map, on_delete=True)
    player = models.ForeignKey(Profile, null=True, on_delete=True)
    resource = models.CharField(choices=RESOURCES, null=True, max_length=10)
    terrain = models.CharField(choices=TERRAIN, null=True, max_length=10)
    col = models.PositiveIntegerField()
    row = models.PositiveIntegerField()
    if_start = models.BooleanField(default=False)

map_engine/views.py
from django.shortcuts import HttpResponseRedirect
from django.shortcuts import render
from django.utils.safestring import mark_safe

from .map_generator.generator import MapCreator
from .map_viewer.main import HexTable
from .models import Map, Field


def list_of_maps(request):
    return render(request, "maps_list.html", {'maps': Map.objects.all()})


def create_new_map(request):
    mc = MapCreator()
    mc.create_map()
    return HttpResponseRedirect("/main")


def show_map(request, map_id):
    fields = Field.objects.filter(map_id=map_id)
    hex_table = HexTable(fields).create()
    return render(request, "map.html", {
        'hex_table': mark_safe(hex_table),
        'map_id': map_id
    })

map_engine/templates/map.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/map_style.css"  type="text/css" media="screen">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <title>Mapa</title>
</head>
<body>

<h1>Mapa: {{ map_id }}</h1>
<div>
    {{ hex_table }}
</div>

</body>
</html>

map_engine/templates/maps_list.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/css/style.css"  type="text/css" media="screen">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <title>Lista Map</title>
</head>
<body>
    <h1><a href="{% url 'map_engine:create_new_map' %}">Stwórz nową mape</a></h1>
    <h1>Lista Map</h1>
    {% for m in maps %}
    <a href="{% url 'map_engine:show_map' map_id=m.id %}">Mapa: {{ m.id }}</a>
    {% endfor %}
</body>
</html>